"""add user consent and name field

Revision ID: f0db078e8fea
Revises: cbb3fb4b5814
Create Date: 2026-10-09 08:56:44.308554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0db078e8fea'
down_revision: Union[str, Sequence[str], None] = 'cbb3fb4b5814'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('first_name', sa.String(length=320), nullable=False))
    op.add_column('users', sa.Column('last_name', sa.String(length=320), nullable=False))
    op.add_column('users', sa.Column('phone', sa.String(length=30), nullable=False))
    op.add_column('users', sa.Column('terms_accepted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('terms_version', sa.String(length=30), nullable=True))
    op.add_column('users', sa.Column('privacy_policy_accepted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('privacy_policy_version', sa.String(length=30), nullable=True))
    op.add_column('users', sa.Column('marketing_consent', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('marketing_consent_updated_at', sa.DateTime(timezone=True), nullable=True))
    op.create_unique_constraint(None, 'users', ['phone'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    # op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'marketing_consent_updated_at')
    op.drop_column('users', 'marketing_consent')
    op.drop_column('users', 'privacy_policy_version')
    op.drop_column('users', 'privacy_policy_accepted_at')
    op.drop_column('users', 'terms_version')
    op.drop_column('users', 'terms_accepted_at')
    op.drop_column('users', 'phone')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    # ### end Alembic commands ###
